---
title: "Rainfall TS Analysis"
author: "Zhiran Tong"
date: "2023-12-01"
output: pdf_document
---

```{r, message=FALSE}
#Data Cleaning
#Filter to Perth and keep date and rainfall columns
library(readr)
library(tidyverse)
library(dplyr)
data = read_csv('Perth_Rainfall.csv')
data$Month <- format(as.Date(paste(data$Month, sep = "","-01"), format = "%y-%b-%d"),"%Y-%m")
data_ts = ts(data$Rainfall)
data = data.frame(ts(data))
plot(x = data$Month, y = data$Rainfall, xlab = "Month", type = "o",
     ylab = "Rainfall (mm)", main = "Monthly Average Rainfall in Perth")
```

```{r}
## Box Jenkins Method
library(TSA)
#Sample ACF
acf(data_ts, lag = length(data_ts), main="Perth Monthly Average
Rainfall\n(ACF)")

#Sample ACF (Two Years)
acf(data_ts, lag = 24, main="Perth Monthly Average Rainfall\n(24 Months)",xlab="Lag (Months)")

#Sample PACF
pacf(data_ts, lag = 24, main= "Perth Monthly Average Rainfall\n(PACF)", xlab="Lag (Months)")

#Sample EACF
eacf(data_ts) ## Maybe a ARMA(3,2), possibly (2,1)
```

```{r}
#Dynamic Method
library(TSA)
library(forecast)

#ARMA(1,0) significant, residual is not white noise
fit10 <- arima(data_ts, order = c(1,0,0))
fit10
ggtsdisplay(fit10$residuals, lag.max=107, main = "ARMA(1,0)")
checkresiduals(fit10)

#ARMA(2,1) significant, residual is not white noise
fit21 <- arima(data_ts, order = c(2,0,1))
fit21
ggtsdisplay(fit21$residuals, lag.max=107, main = "ARMA(2,1)")
checkresiduals(fit21)

#ARMA(3,2) significant, residual is not white noise
fit32 <- arima(data_ts, order = c(3,0,2))
fit32
ggtsdisplay(fit32$residuals, lag.max=107, main = "ARMA(3,2)")
checkresiduals(fit32)


#ARMA(2,1)x(1,0) significant, 2se does not drop it lower than 0
#This is potentially our best model
#Residual very close to white noise, 2 lags are a little significant but no big deal
#aic or se^2 is for model comparison, see if using a different model changes them a lot
fit2110 <- arima(data_ts, order = c(2,0,1), seasonal = list(order = c(1,0,0), period = 12))
fit2110
ggtsdisplay(fit2110$residuals, lag.max=107, main = "ARMA(2,1)x(1,0)12")
checkresiduals(fit2110)

#ARMA(2,1)x(2,1) significant, residual is not white noise
fit2121 <- arima(data_ts, order = c(2,0,1), seasonal = list(order = c(2,0,1), period = 12))
fit2121
ggtsdisplay(fit2121$residuals, lag.max=107, main = "ARMA(2,1)x(2,1)12")
checkresiduals(fit2121)



```

```{r}
#data = read_csv('weatherAUS.csv')
# calculating proportion of missing data
# data = data[, c(1, 2, 5)]
# sum(is.na(data))/nrow(data)
#data = data[data$Location == "Perth", c(1, 2, 5)]
#data$Date <- as.Date(data$Date)
# daily rainfall
# data_d = data.frame(ts(data))
# plot(x = data_d$Date, y = data_d$Rainfall, xlab = "Daily", type = "o",
#      ylab = "Rainfall (mm)", main = "Daily Average Rainfall in Perth")
# fit1 <- arima(data_ts, order = c(2,0,1), seasonal = list(order = c(1,0,1), period= 12))
# fit1

#Forecasting
fore2110 <- forecast(data_ts,model = fit2110, h = 12)
plot(fore2110, xlab = "Month", ylab = "Precipitation (mm)",main = "12 Month
Precipitation Forecast Using ARMA(2,1)x(1,0)12")
```

```{r}

# Code for figure 3.1 . 
library(readr)

new<- read_csv("IDCJAC0009_009021_1800_Data.csv") #daily dataset
new = new[, c(3,4,5,6)]
new = new[new$Year > "2007",]
new$Date = paste(new$Year, new$Month, new$Day, sep = "-")

new$Date <- as.Date(new$Date)
new$Month <- format(new$Date, "%Y-%m")
new <- new[new$Date >= "2008-07-01" & new$Date <= "2018-06-25",]# original data is ended at 2017-06-25 so one more year
original = new[new$Date >= "2008-07-01" & new$Date <= "2017-06-25",]
nrow(original)

new = new[,c(2,4)]
original = original[,c(2,4)]
colnames(new) = c("Month", "Rainfall")
colnames(original) = c("Month", "Rainfall")
# new %>% is.na() %>% sum() no NA


new <- aggregate(Rainfall ~ Month, data = new, FUN = mean, na.rm = TRUE)
nrow(new)
original = aggregate(Rainfall ~ Month, data = original, FUN = mean, na.rm = TRUE)
nrow(original)

new_ts = ts(new$Rainfall)
original_ts = ts(original$Rainfall)
new = data.frame(ts(new))
original = data.frame(ts(original))

# i dont recommend running the code, i will post the result of the plot on whatsapp

#plot(x = new$Month, y = new$Rainfall, xlab = "Month", type = "o",
#     ylab = "Rainfall (mm)", main = "Actual Monthly Average Rainfall in Perth #(108 + 12 Month)") 
#points(x = original$Month, y = original$Rainfall, col = "blue", pch = 16, type = "l")
##points(x = data$Month, y = data$Rainfall, col = "red", pch = 16, type = "l")
#abline(v = 108, col = "blue", lty = 2)
#legend("topright", legend = c( "Extended Period"),
#       col = c( "blue"), pch = 16, lty =2, cex = 0.8)
```


